apiVersion: v1
kind: Pod
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  containers:
  - name: goserver
    image: "atilarampazo/hello-go:latest"
  #- name: nginx
    #image: nginx/nginx
